use_frameworks!
inhibit_all_warnings!
source 'https://github.com/ShannonCrazy/XGCMainSpecs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'XGCScan_Example' do
  pod 'XGCScan', :path => '../'

  target 'XGCScan_Tests' do
    inherit! :search_paths
  end
end
